version: "3"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
    depends_on:
      - fastapi
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules

  fastapi:
    build: ./api
    ports:
      - "5000:80"
